parameters:
  Name: ''
  dockerimagename: ''
  dockerimagetag: ''
  dockerapppath: ''
  dockerfile: ''
  dockerbuildargs: ''
  AgentPoolName: ''
  ArtifactName: ''
  dockerimagescan: ''

jobs: 
- job: ${{ parameters.Name }}DockerBuildAndPublish
  ### Uses PrepForBuild Job from downstream pipeline. This dependency is for teams to make changes in their directory structure 
  ### E.g. Config transforms, seed data, etc...
  pool:
      name: ${{ parameters.AgentPoolName }} # Valid Values: 'OnPremAgents' - Hosted:'Hosted VS2017',  'Hosted macOS', 'Hosted Ubuntu 1604'
  workspace:
    clean: all
  steps:
  ## Application Build:  Builds the Application, Runs the Unit Tests
  - template: ../Docker/DockerBuildAndPublish.yml  # Template reference
    parameters:
      Name: ${{ parameters.Name }}
      dockerimagename: ${{ parameters.dockerimagename }}
      dockerapppath:  ${{ parameters.dockerapppath }}
      dockerfile:  ${{ parameters.dockerfile }}   
      dockerbuildargs:  ${{ parameters.dockerbuildargs }}   
      dockerimagetag: ${{ parameters.dockerimagetag }}  
      ArtifactName: ${{ parameters.ArtifactName }} 
      dockerimagescan: ${{ parameters.dockerimagescan }} 
    
  - powershell: Echo Endpoint $(DockerImageEndpoint)
    displayName: 'Show Image location and current Docker Build Tag'  
